### ISSUE TITLE
Add widgets and alarms for AWS AppSync resources

### ISSUE THREAD

**Issue by direnakkoc** [fourTheorem/slic-watch#103]
Create metrics for alarms and dashboards:

## Alarms
- 5XXError
- Latency

## Dashboard Widgets
One widget for:
- 5XXError
- 4XXError
- Latency
- Requests

A second widget for subscriptions:
- ConnectServerError
- DisconnectServerError
- SubscribeServerError
- UnsubscribeServerError
- PublishDataMessageServerError

**Comment by eoinsha** [comment]
Resolved with #105
