### ISSUE TITLE
Metada access of undefined

### ISSUE THREAD

**Issue by Lschulzes** [fourTheorem/slic-watch#117]
**Describe the bug**
When trying to deploy I get the error.
Proposed solution at #118 
**To Reproduce**
1. sls deploy

**Expected behavior**

**Screenshots, Input Files and Logs**
If applicable, add screenshots, CloudFormation templates, serverless configuration and/or logs to help explain your problem.
![image](https://github.com/fourTheorem/slic-watch/assets/77251840/86a45824-5976-4966-a4dc-c137be7fb737)

**Environment:**
 - OS:   WSL
 - Node.js Version:  20.0.0
 - NPM version:  10.7.0
 - Serverless Framework Version:   >=3.35.2

**Additional context**

**Comment by Lschulzes** [comment]
@eoinsha Hey there, can you let me know if there is something I can do?

**Comment by eoinsha** [comment]
This has been resolved in `v3.2.1`
