### ISSUE TITLE
Add SQS alarms and widgets

### ISSUE THREAD

**Issue by eoinsha** [fourTheorem/slic-watch#29]

**Comment by lmammino** [comment]
Possible alarms to support:

 - `NumberOfMessagesSent` < threshold (average amount of messages produced in the last 5 min under threshold) - optional
 - `NumberOfMessagesSent` > threshold (average amount of messages produced in the last 5 min above threshold) - optional
 - `ApproximateAgeOfOldestMessage` > threshold (approximate age of the oldest message in the queue above threshold: messages aren't processed fast enough) - optional
 - `ApproximateNumberOfMessagesNotVisible` > threshold (approximate number of messages in flight above threshold) - enabled with default threshold `96_000 ` (80% of the hard limit of `120_000`)
 -  `ApproximateNumberOfMessagesNotVisible` > threshold (FIFO queue) (approximate number of messages in flight above threshold) - enabled with default threshold `14_400 ` (80% of the hard limit of `18_000`)
 - `ApproximateNumberOfMessagesVisible` > threshold (approximate number of messages in the queue exceeds threshold. Can be useful to alert if data is going into a dead letter queue, but we will need to have a way to distinguish between regular queues and DLQs) - optional

Source: https://www.bluematador.com/blog/how-to-monitor-amazon-sqs-with-cloudwatch
