### ISSUE TITLE
CDK Support

### ISSUE THREAD

**Issue by brianfoody** [fourTheorem/slic-watch#65]
**Is your feature request related to a problem? Please describe.**
No problem at all, love the look of the solution. Just wondering if you plan on supporting CDK in future?

**Describe the solution you'd like**
A CDK construct to wrap around primitives and add this observability.

**Describe alternatives you've considered**
https://constructs.dev/packages/cdk-watchful/v/0.5.233?lang=typescript

**Additional context**
Nope just curious if this is on your roadmap.

**Comment by eoinsha** [comment]
CDK Support is now available in the SLIC Watch CloudFormation Macro. The [README](https://github.com/fourTheorem/slic-watch/blob/main/README.md#getting-started-with-aws-sam-cdk-or-cloudformation) has all the details on how to get going!
