### ISSUE TITLE
Replace Lerna

### ISSUE THREAD

**Issue by lmammino** [fourTheorem/slic-watch#79]
⚠️ Lerna is not supported anymore.

From the [official Lerna readme](https://github.com/lerna/lerna#readme):

> Important note: this project https://github.com/lerna/lerna/issues/2703. Consider adopting an alternative toolset for monorepo management.

We should future-proof SLIC Watch and switch from Lerna to something else.

One of the options I was pointed at is [nx](https://nx.dev/) and there is also a [guide on how to migrate from Lerna to nx](https://blog.nrwl.io/migrating-from-lerna-to-nx-better-dev-ergonomics-much-faster-build-times-da76ff14ccbb).

Another potentially interesting option is [TurboRepo](https://turborepo.org/), recently acquired by Vercel. This one [is said to work very well in combination with pnpm](https://twitter.com/jkomyno/status/1519647290423713792).

**Comment by eoinsha** [comment]
Lerna has been replaced by NPM Workspaces as part of Release 2!
